### ISSUE TITLE
可以提供一个ElasticSearch增删改查的demo吗？

### ISSUE THREAD

**Issue by hnsongbiao** [wulaiwei/WorkData.Core#1]
可以提供一个ElasticSearch增删改查的demo吗？
配置项如何配置，如何连接？

**Comment by wulaiwei** [comment]
你好这边已经上传了测试项目https://github.com/wulaiwei/WorkData.Core/tree/master/WorkData/WorkDataEs  
你需要更改配置文件 
https://github.com/wulaiwei/WorkData.Core/blob/master/WorkData/WorkDataEs/Config/commonConfig.json
参数"Uri": "http://*:*",
为你的Es服务端 ip及端口即可
